# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3b377761b85779f09b7be5e5be4e17514f76adfda63af0496d743dd4c962f2b62dd79831bacfa114a35bceccc7c12d6b06fb62391af28bb342ff44a976fec217

test:
  secret_key_base: bcb340142eeed67d71d995e7493dfa2e0d8617542436f7d22a98feb6d9f5b88e0c15a1c626398832786bcf0dfc4db558eb92b36aa8dbdb3f476c1e3f6b0ca374

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
